### ISSUE TITLE
Problem with check-snmp-disk.rb

### ISSUE THREAD

**Issue by xblitz** [sensu-plugins/sensu-plugins-snmp#11]
at https://github.com/sensu-plugins/sensu-plugins-snmp/blob/master/bin/check-snmp-disk.rb#L107 it seems that it only takes the last character to determine which snmp OID has the desired mount point..  but it should take the last interger seperated by the dot.
maybe something like:
`var.name.split(".")[-1]`
but I don't know ruby so much

**Comment by majormoses** [comment]
That looks sane without jumping into the code. I would take a PR to fix that up.

**Comment by xblitz** [comment]
actually after testing, it was the "-m" parameter that is actually evaluated as a regex that was causing my issues.   the [-1] is actually good with the SNMP object. this issue can be closed
