### ISSUE TITLE
walk timeout get not responding error

### ISSUE THREAD

**Issue by rocdove** [sensu-plugins/sensu-plugins-snmp#22]
snmp.interfaces.1651.ifHCInOctets 80789010008763 1529376492
snmp.interfaces.1651.ifHCOutOctets 87961849872358 1529376492
snmp.interfaces.1652.ifHCInOctets 74822559856289 1529376492
snmp.interfaces.1652.ifHCOutOctets 84320870725777 1529376492
Check failed to run: host <IP> not responding, ["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/snmp-1.2.0/lib/snmp/manager.rb:279:in `get_next'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/snmp-1.2.0/lib/snmp/manager.rb:439:in `block in walk'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/snmp-1.2.0/lib/snmp/manager.rb:438:in `loop'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/snmp-1.2.0/lib/snmp/manager.rb:438:in `walk'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-snmp-0.2.0/bin/metrics-snmp-if.rb:142:in `block in run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/snmp-1.2.0/lib/snmp/manager.rb:218:in `open'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-snmp-0.2.0/bin/metrics-snmp-if.rb:141:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.4/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]

Timeout option in snmp/manager.rb ,it default is 1s -- too short.
I want to set timeout in metrics-snmp-if.rb
`  ...
   option :timeout,
         short: '-t TIMEOUT',
         long: '--timeout TIMEOUT',
         default: 5,
         description: 'Request timeout'

  def run # rubocop:disable Metrics/AbcSize
     ...
    SNMP::Manager.open(host: config[:host].to_s, community: config[:community].to_s, version: config[:version], timeout: config[:timeout]) do |manager|
      manager.walk(if_table_columns) do |row_array|
`

**Comment by majormoses** [comment]
closed via #23
